FUSEINC=/usr/include/fuse

FUSELIB=fuse

#PATH=/root/buildroot-2009.05/build_i686/staging_dir/usr/bin/:/usr/bin/:/bin/:/sbin:/usr/sbin

#gcc=i686-linux-uclibc-gcc

#CFLAGS:=$(CFLAGS) -DBRINTF_FILEOUT=1 # use default printf - no locking
# add -pg here for gprof? Not getting good data out of there right now

crestfs: crestfs.dynamic
	cp crestfs.dynamic crestfs
